#!/usr/bin/python3
# -*- coding:UTF-8 -*-

def model_exception(x,y):
    try:
        b = name
        a = x/y
    except:
         print('Error happened')

model_exception(2,'')
